ESLint:
  script:
    - npm install
    - npm run eslint
  tags:
    - general_cent7
SassLint:
  script:
    - npm install
    - npm run sasslint
  tags:
    - general_cent7
Prettier:
  script:
    - npm install
    - npm run prettier
  tags:
    - general_cent7
Jest:
  script:
    - npm install
    - npm run test:ci
  tags:
    - general_cent7
Deploy Dev:
  script:
    - bundle install --path ~/vendor/bundle
    - bundle exec cap dev deploy
  type: deploy
  tags:
    - cap_deploy
  only:
    - master
Deploy Stage:
  script:
    - bundle install --path ~/vendor/bundle
    - bundle exec cap stage deploy
  type: deploy
  tags:
    - cap_deploy
  only:
    - stage
Deploy Prod:
  script:
    - bundle install --path ~/vendor/bundle
    - bundle exec cap prod deploy
  type: deploy
  tags:
    - cap_deploy
  only:
    - prod
