ESLint:
  script:
    - yarn install
    - yarn eslint
  tags:
    - general_cent7
SassLint:
  script:
    - yarn install
    - yarn sasslint
  tags:
    - general_cent7
Prettier:
  script:
    - yarn install
    - yarn prettier
  tags:
    - general_cent7
Jest:
  script:
    - yarn install
    - yarn test:ci
  tags:
    - general_cent7
Deploy Dev:
  script:
    - bundle install --path ~/vendor/bundle
    - bundle exec cap dev deploy
  type: deploy
  tags:
    - cap_deploy
  only:
    - master
Deploy Stage:
  script:
    - bundle install --path ~/vendor/bundle
    - bundle exec cap stage deploy
  type: deploy
  tags:
    - cap_deploy
  only:
    - stage
Deploy Prod:
  script:
    - bundle install --path ~/vendor/bundle
    - bundle exec cap prod deploy
  type: deploy
  tags:
    - cap_deploy
  only:
    - prod
