version: '3'
services:
  web:
    build: .
    volumes:
      - .:/opt/mprnews
      - nodemodules:/opt/mprnews/node_modules
      - nodebuild:/opt/mprnews/build
    ports:
      - "3001:3000"

volumes:
  nodemodules:
  nodebuild:
