version: '3'
services:
  web:
    build: 
      context: .
      #      dockerfile: Dockerfile.stretch
      args:
        - APP_USER_UID=${APP_USER_UID}
        - APP_GROUP_GID=${APP_GROUP_GID}
    volumes:
      - .:/opt/mprnews
      - nodemodules:/opt/mprnews/node_modules
      - nodebuild:/opt/mprnews/build
    ports:
      - "3001:3000"

volumes:
  nodemodules:
  nodebuild:
