query contributions(
  $contentAreaSlug: String!
  $slug: String!
  $pageNum: Int
  $id: String!
) {
  profile(contentAreaSlug: $contentAreaSlug, slug: $slug, id: $id) {
    collection: contributionResults(page: $pageNum, pageSize: 10) {
      totalPages
      currentPage
      previousPage
      nextPage
      items {
        id
        title
        description
        publishDate
        canonicalSlug
        resourceType
      }
    }
  }
}
