query profile($contentAreaSlug: String!, $slug: String!, $previewToken: String) {
  profile: profile(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    subtitle
    canonicalSlug
    publishDate
    body
    description
    resourceType
    embeddedAssetJson
    contributions(
      page:1
    ) {
      title
      description
      publishDate
      id
      resourceType
    }
    primaryVisuals {
      lead {
        aspect_ratios: aspectRatios {
          uncropped {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        credit {
          name
          url
        }
        dateTaken
        dateline
        fallback
        longCaption
        shortCaption
        xid
      }
    }
  }
}
