query profile(
  $contentAreaSlug: String!
  $slug: String!
  $pageNum: Int
  $previewToken: String
) {
  profile: profile(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    jobTitle
    canonicalSlug
    publishDate
    body
    email
    description
    descriptionText
    resourceType
    embeddedAssetJson
    results: contributionResults(page: $pageNum, pageSize: 10) {
      totalPages
      currentPage
      previousPage
      nextPage
      items {
        id
        title
        description
        publishDate
        canonicalSlug
        resourceType
      }
    }
    profileRelatedLinks {
      uri
      text
    }
    primaryVisuals {
      social {
        fallback
      }
      lead {
        aspect_ratios: aspectRatios {
          uncropped {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        credit {
          name
          url
        }
        fallback
        longCaption
        shortCaption
        xid
      }
    }
  }
}
