query collection($contentAreaSlug: String!, $slug: String!, $pageNum: Int) {
  collection: collection(contentAreaSlug: $contentAreaSlug, slug: $slug) {
    id
    title
    body
    embeddedAssetJson
    results(page: $pageNum, pageSize: 10) {
      nextPage
      pageSize
      totalPages
      totalItems
      previousPage
      currentPage
      items {
        id
        title
        publishDate
        description
        canonicalSlug
        resourceType
        audio {
          encodings {
            httpFilePath
            durationMs
            durationHms
          }
        }
        contributors {
          profile {
            firstName
            lastName
          }
        }
        primaryVisuals {
          lead {
            aspect_ratios: aspectRatios {
              uncropped {
                instances {
                  url
                  width
                  height
                }
              }
              widescreen {
                instances {
                  url
                  width
                  height
                }
              }
            }
            contentArea
            dateTaken
            dateline
            fallback
            longCaption
            shortCaption
            xid
          }
        }
        audio {
          title
          durationHms
          encodings {
            httpFilePath
          }
        }
        ... on Link {
          destination
        }
      }
      totalItems
      nextPage
    }
  }
}
