query story($contentAreaSlug: String!, $slug: String!, $previewToken: String) {
  story: story(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    subtitle
    dateline
    canonicalSlug
    primaryCollection {
      title
      canonicalSlug
    }
    contributors {
      profile {
      	title
        canonicalSlug
      }
      roles {
        name
      }
    }
    publishDate
    body
    description
    resourceType
    primaryAudio {
      title
      credit
      durationHms
      durationMs
      encodings {
        format
        mediaType
        httpFilePath
        playFilePath
      }
    }
    embeddedAssetJson
    primaryVisuals {
      lead {
        aspect_ratios: aspectRatios {
          uncropped {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        credit {
          name
          url
        }
        dateTaken
        dateline
        fallback
        longCaption
	rights {
	  redistributable
	}
        shortCaption
        xid
      }
    }
  }
}
