query story($contentAreaSlug: String!, $slug: String!, $previewToken: String) {
  story: story(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    subtitle
    canonicalSlug
    collections {
      title
      canonicalSlug
    }
    contributors {
      profile {
        firstName
        lastName
        canonicalSlug
      }
      roles {
        name
      }
    }
    publishDate
    body
    description
    resourceType
    embeddedAssetJson
    primaryVisuals {
      lead {
        aspectRatios {
          square {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        credit {
          name
          url
        }
        dateTaken
        dateline
        fallback
        longCaption
        shortCaption
        xid
      }
    }
  }
}
