query story($contentAreaSlug: String!, $slug: String!, $previewToken: String) {
  story: story(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    subtitle
    supportedOutputFormats
    resourceType
    dateline
    canonicalSlug
    primaryCollection {
      id
      title
      canonicalSlug
    }
    contributors {
      profile {
        id
        title
        canonicalSlug
      }
      roles {
        name
      }
    }
    publishDate
    body
    description
    descriptionText
    resourceType
    primaryAudio {
      title
      credit
      durationHms
      durationMs
      encodings {
        format
        mediaType
        httpFilePath
        filename
        playFilePath
      }
    }
    embeddedAssetJson
    primaryVisuals {
      social {
        aspect_ratios: aspectRatios {
          uncropped {
            instances {
              url
              width
              height
            }
          }
          widescreen {
            instances {
              url
              width
              height
            }
          }
        }
        fallback
      }
      lead {
        preferredAspectRatio {
          instances {
            url
            width
            height
          }
        }
        aspect_ratios: aspectRatios {
          uncropped {
            instances {
              url
              width
              height
            }
          }
          widescreen {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        credit {
          name
          url
        }
        dateTaken
        dateline
        fallback
        longCaption
        rights {
          redistributable
        }
        shortCaption
        xid
      }
    }
  }
  alertConfig: potlatch(slug: "mprnews/info-alert") {
    slug
    json
  }
}
