query photoGallery($contentAreaSlug: String!, $slug: String!) {
  gallery: episode(contentAreaSlug: $contentAreaSlug, slug: $slug) {
    id
    title
    canonicalSlug
    publishDate
    body
    embeddedAssetJson
    primaryVisuals {
      thumbnail {
        aspectRatios {
          normal {
            instances {
              url
              width
              height
            }
          }
          portrait {
            instances {
              width
              height
              url
            }
          }
          widescreen {
            instances {
              width
              height
              url
            }
          }
        }
        contentArea
        dateTaken
        dateline
        fallback
        longCaption
        shortCaption
        xid
      }
    }
  }
}
