query home($contentAreaSlug: String!, $slug: String!) {
  homeList: collection(contentAreaSlug: $contentAreaSlug, slug: $slug) {
    id
    title
    description
    descriptionText
    results(page: 1, pageSize: 20) {
      items {
        id
        title
        canonicalSlug
        resourceType
        description
        descriptionText
        primaryVisuals {
          thumbnail {
            aspect_ratios: aspectRatios {
              thumbnail {
                instances {
                  width
                  height
                  url
                }
              }
              widescreen {
                instances {
                  width
                  height
                  url
                }
              }
              uncropped {
                instances {
                  url
                  width
                  height
                }
              }
            }
            contentArea
            dateTaken
            dateline
            fallback
            longCaption
            shortCaption
            xid
          }
        }
        audio {
          id
          title
          durationHms
          encodings {
            httpFilePath
            durationMs
          }
        }
        collectionRelatedLinks {
          url
          title
          prefix
        }
        ... on Link {
          destination
        }
      }
    }
  }
  updraft: collection(
    contentAreaSlug: $contentAreaSlug
    slug: "weather-and-climate/updraft"
  ) {
    id
    results(page: 1, pageSize: 1) {
      items {
        id
        title
        resourceType
        canonicalSlug
      }
    }
  }
  alertConfig: potlatch(slug: "mprnews/alerts1") {
    slug
    json
  }
  homeStoryConfig: potlatch(slug: "mprnews/homepage-stories") {
    slug
    json
  }
}
