query episode($contentAreaSlug: String!, $slug: String!) {
  episode: episode(contentAreaSlug: $contentAreaSlug, slug: $slug) {
    id
    title
    canonicalSlug
    publishDate
    body
    embeddedAssetJson
    primaryVisuals {
      lead {
        aspect_ratios: aspectRatios {
          widescreen {
            instances {
              url
              width
              height
            }
          }
          uncropped {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        dateTaken
        dateline
        fallback
        longCaption
        shortCaption
        xid
      }
    }
    audio {
      title
      durationHms
      encodings {
        httpFilePath
      }
    }
  }
}
