query episode(
  $contentAreaSlug: String!
  $slug: String!
  $previewToken: String
) {
  episode: episode(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    subtitle
    canonicalSlug
    supportedOutputFormats
    primaryCollection {
      id
      title
      canonicalSlug
    }
    contributors {
      profile {
        id
        firstName
        lastName
        canonicalSlug
      }
      roles {
        name
      }
    }
    publishDate
    body
    description
    descriptionText
    resourceType
    primaryAudio {
      id
      title
      credit
      durationHms
      durationMs
      encodings {
        format
        mediaType
        httpFilePath
        playFilePath
      }
    }
    embeddedAssetJson
    primaryVisuals {
	social {
	  aspect_ratios: aspectRatios {
	    uncropped {
              instances {
                url
                width
                height
              }
            }
	    widescreen {
              instances {
                url
                width
                height
              }
            }
          }
        fallback
      }
      lead {
        preferredAspectRatio {
          instances {
            url
            width
            height
          }
        }
        aspect_ratios: aspectRatios {
          uncropped {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        credit {
          name
          url
        }
        dateTaken
        dateline
        fallback
        longCaption
        shortCaption
        xid
      }
    }
  }
  alertConfig: potlatch(slug: "mprnews/info-alert") {
    slug
    json
  }
}
