query episodeQuery($contentAreaSlug: String!, $slug: String!) {
  episode: episode(contentAreaSlug: $contentAreaSlug, slug: $slug) {
    id
    title
    canonicalSlug
    publishDate
    body
    description
    resourceType
    embeddedAssetJson
    primaryVisuals {
      lead {
        aspectRatios {
          square {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        dateTaken
        dateline
        fallback
        longCaption
        shortCaption
        xid
      }
    }
  }
}
