query PageQuery(
  $contentAreaSlug: String!
  $slug: String!
  $previewToken: String
) {
  page: page(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    canonicalSlug
    descriptionText
    supportedOutputFormats
    primaryVisuals {
      social {
        fallback
      }
    }
    primaryCollection {
      id
      title
      canonicalSlug
    }
    publishDate
    body
    embeddedAssetJson
  }
}
