query PageQuery(
  $contentAreaSlug: String!
  $slug: String!
  $previewToken: String
) {
  page: page(
    contentAreaSlug: $contentAreaSlug
    slug: $slug
    previewToken: $previewToken
  ) {
    id
    title
    originalSourceUrl
    canonicalSlug
    descriptionText
    supportedOutputFormats
    primaryVisuals {
      social {
        aspect_ratios: aspectRatios {
          uncropped {
            instances {
              url
              width
              height
            }
          }
          widescreen {
            instances {
              url
              width
              height
            }
          }
        }
        fallback
      }
    }
    primaryCollection {
      id
      title
      canonicalSlug
    }
    publishDate
    body
    embeddedAssets {
      audio
      attachments
      images
      oembeds
    }
  }
}
