query home($contentAreaSlug: String!, $slug: String!) {
  story: story(contentAreaSlug: $contentAreaSlug, slug: $slug) {
    title
    publishDate
    description
    body
    embeddedAssetJson
    resourceType
  }
}
