query story($contentAreaSlug: String!, $slug: String!) {
  story: story(contentAreaSlug: $contentAreaSlug, slug: $slug) {
    title
    publishDate
    description
    body
    embeddedAssetJson
    resourceType
    primaryVisuals {
      lead {
        aspectRatios {
          square {
            instances {
              url
              width
              height
            }
          }
        }
        contentArea
        dateTaken
        dateline
        fallback
        longCaption
        shortCaption
        xid
      }
    }
  }
}
